---
  - name: Read-replica nodes setup
    hosts: pgread
    become: yes
    become_method: sudo
    gather_facts: yes
    tags: [readreplica]
    vars:
      - replica_username: 'pgreplica'
      - replica_password: 'P@ss99W0rd_replica'
    tasks:
      - name: Create directory to hold WAL archive files
        file:
          path: /var/lib/pgsql/11/walarchive/
          state: directory
          owner: postgres
          mode: '0760'
      - name: Set Postgres required parameters
        become: yes
        become_user: postgres
        with_items:
          # REPLICATION
          - { name: 'hot_standby', value: 'on' }
          - { name: 'hot_standby_feedback', value: 'on' }
        postgresql_set:
          name: "{{ item.name }}"
          value: "{{ item.value }}"
      - name: Temporarily stop PostgreSQL service
        systemd:
          name: postgresql-11
          state: stopped
      - name: Import base backup of the primary to the standby database
        become: yes
        become_user: postgres
        shell: | 
          ./pg_basebackup -D /var/lib/pgsql/11/data/ -c fast -X fetch -P -Fp -R -h {{ hostvars[groups['pgmaster'][0]].ansible_host }} -p 5432 -U {{ replica_username }}

          expect 'Password:'
          send {{ replica_password }}

          exit 0
        args:
          chdir: /usr/pgsql-11/bin/
      - name: Start PostgreSQL service
        systemd:
          name: postgresql-11
          state: started