---
  - name: Read-replica nodes setup
    hosts: pgread
    become: yes
    become_method: sudo
    gather_facts: yes
    tags: [readreplica]
    vars:
      - db_name: equator_dev  
      - db_password: 'P@ss99W0rd'
      - pg_data_dir: /data/equator
    tasks:
      - name: Create directory to hold WAL archive files
        path: /var/lib/pgsql/11/walarchive/
        state: directory
        owner: postgres
        mode: '0760'
        
