---
  - name: Master nodes setup
    hosts: pgmaster
    become: yes
    become_method: sudo
    gather_facts: yes
    tags: [master]
    vars:
      - db_name: equator_dev
      - db_username: eq_db
      - db_password: 'P@ss99W0rd'
      - pg_data_dir: /data/equator  # Not use yet. Need look in to this if datastorage is mount in different place
      - replica_username: 'pgreplica'
      - replica_password: 'P@ss99W0rd_replica'
      # Caculated using https://pgtune.leopard.in.ua
      - max_connections: 200
      - shared_buffers: 256MB
      - effective_cache_size: 768MB
      - maintenance_work_mem: 64MB
      - checkpoint_completion_target: 0.7
      - wal_buffers: 7864kB
      - default_statistics_target: 100
      - random_page_cost: 1.1
      - effective_io_concurrency: 200
      - work_mem: 2621kB
      - min_wal_size: 1GB
      - max_wal_size: 2GB
      - max_worker_processes: 2
      - max_parallel_workers_per_gather: 1
      - max_parallel_workers: 2
      - wal_level: replica
      - max_wal_senders: 10
      - wal_keep_segments: 256
      - archive_mode: 'on'
      - archive_command: /usr/pgsql-11/bin/syncwal.sh
    tasks:
      - name: Create Equator database
        become: yes
        become_user: postgres
        postgresql_db:
          name: "{{ db_name }}"
          encoding: UTF-8
          lc_collate: en_US.UTF-8
          lc_ctype: en_US.UTF-8
          conn_limit: "{{ max_connections | int }}"

      - name: Set Postgres required parameters
        become: yes
        become_user: postgres
        with_items:
          - { name: 'shared_buffers', value: "{{ shared_buffers }}" }
          - { name: 'effective_cache_size', value: "{{ effective_cache_size }}" }
          - { name: 'checkpoint_completion_target', value: "{{ checkpoint_completion_target }}" }
          - { name: 'wal_buffers', value: "{{ wal_buffers }}" }
          - { name: 'default_statistics_target', value: "{{ default_statistics_target }}" }
          - { name: 'random_page_cost', value: "{{ random_page_cost }}" }
          - { name: 'effective_io_concurrency', value: "{{ effective_io_concurrency }}" }
          - { name: 'work_mem', value: "{{ work_mem }}" }
          - { name: 'min_wal_size', value: "{{ min_wal_size }}" }
          - { name: 'max_wal_size', value: "{{ max_wal_size }}" }
          - { name: 'max_worker_processes', value: "{{ max_worker_processes }}" }
          - { name: 'max_parallel_workers_per_gather', value: "{{ max_parallel_workers_per_gather }}" }
          - { name: 'max_parallel_workers', value: "{{ max_parallel_workers }}" }
          # REPLICATION
          - { name: 'wal_level', value: "{{ wal_level }}" }
          - { name: 'max_wal_senders', value: "{{ max_wal_senders }}" }
          - { name: 'wal_keep_segments', value: "{{ wal_keep_segments }}" }
          - { name: 'archive_mode', value: "{{ archive_mode }}" }
          - { name: 'archive_command', value: "{{ archive_command }}" }
          - { name: 'effective_cache_size', value: "{{ effective_cache_size }}" }
        postgresql_set:
          name: "{{ item.name }}"
          value: "{{ item.value }}"
      - name: Copy script to copy WAL files from primary to standby
        copy:
          content: |
            #!/bin/sh
            scp -o StrictHostKeyChecking=no -q $1 {{ hostvars['psql3'].ansible_host }}:/var/lib/pgsql/11/walarchive/$2
            if [ $? != 0 ]
            then
              echo 'Archiver error:'
              exit 1
            fi
            exit 0
          dest: "{{ archive_command }}"
          owner: postgres
          group: postgres
          mode: '0760'
      - name: Create replica user, set MD5-hashed password, grant replication privs
        become: yes
        become_user: postgres
        postgresql_user:
          name: "{{ replica_username }}"
          password: "{{ replica_password }}"
          encrypted: yes
          expires: infinity
          role_attr_flags: LOGIN
      - name: Create replica user, set MD5-hashed password, grant replication privs
        become: yes
        become_user: postgres  
        postgresql_query:
          db: postgres
          query: "ALTER USER {{ replica_username }} WITH REPLICATION;"
      - name: Setup Replica node access in pg_hba
        become: yes
        become_user: postgres
        postgresql_pg_hba:
          dest: /var/lib/pgsql/11/data/pg_hba.conf
          address: "{{ hostvars['psql3'].ansible_host }}/32"
          contype: host
          users: "{{ replica_username }}"
          databases: replication
          method: md5
      - name: Restart PostgreSQL service to take new configs
        systemd:
          name: postgresql-11
          state: restarted