---
  - name: Master node setup
    hosts: psql1
    become: yes
    become_method: sudo
    gather_facts: yes
    tags: [master]
    vars:
      - db_name: equator_dev
      - db_username: eq_db
      - db_password: 'P@ss99W0rd'
      - pg_data_dir: /data/equator
      # Caculated using https://pgtune.leopard.in.ua
      - max_connections: 200
      - shared_buffers: 2GB
      - effective_cache_size: 6GB
      - maintenance_work_mem: 512MB
      - checkpoint_completion_target: 0.9
      - wal_buffers: 16MB
      - default_statistics_target: 100
      - random_page_cost: 1.1
      - effective_io_concurrency: 300
      - work_mem: 5242kB
      - min_wal_size: 2GB
      - max_wal_size: 4GB
    tasks:
      - name: Create Equator database
        become: yes
        become_user: postgres
        postgresql_db:
          name: "{{ db_name }}"
          encoding: UTF-8
          lc_collate: en_US.UTF-8
          lc_ctype: en_US.UTF-8
          conn_limit: "{{ max_connections }}"
      - name: Set memory shared buffers parameter
        become: yes
        become_user: postgres
        postgresql_set:
          name: shared_buffers
          value: "{{ shared_buffers }}"
      - name: Set memory cache size parameter
        become: yes
        become_user: postgres
        postgresql_set:
          name: effective_cache_size
          value: "{{ effective_cache_size }}"
      - name: Set memory for maintenance work parameter
        become: yes
        become_user: postgres
        postgresql_set:
          name: effective_cache_size
          value: "{{ effective_cache_size }}"
      - name: Set checkpoint_completion_target parameter
        become: yes
        become_user: postgres
        postgresql_set:
          name: checkpoint_completion_target
          value: "{{ checkpoint_completion_target }}"
      - name: Set wal_buffers parameter
        become: yes
        become_user: postgres
        postgresql_set:
          name: wal_buffers
          value: "{{ wal_buffers }}"
      - name: Set default_statistics_target parameter
        become: yes
        become_user: postgres
        postgresql_set:
          name: default_statistics_target
          value: "{{ default_statistics_target }}"      
      
